# Generated by Django 4.0.3 on 2022-06-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('tel', models.CharField(help_text='Enter number with Country Code Eg. 771339090', max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Societé',
                'verbose_name_plural': 'Societés',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Prenom')),
                ('lastname', models.CharField(max_length=30, verbose_name='Nom')),
                ('tel', models.CharField(max_length=9, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('society_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structures.society', verbose_name='Societé')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
