# Generated by Django 4.0.3 on 2022-06-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'Agent')], default='agent', max_length=7, verbose_name='Role'),
        ),
    ]
