# Generated by Django 4.0.3 on 2022-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
