# Generated by Django 4.0.3 on 2022-06-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0006_employee_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_time', models.DateTimeField(auto_now_add=True, verbose_name='pointage debut')),
                ('status', models.CharField(blank=True, choices=[('absent', 'absent'), ('retard', 'retard'), ('regle', 'en regle')], max_length=50, verbose_name='Status')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fait le')),
                ('updated', models.DateField(auto_now=True, verbose_name='mise a jour le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqrApp.employee', verbose_name='Employé')),
            ],
        ),
    ]
