# Generated by Django 4.0.3 on 2022-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0008_pointing_clock_out_alter_pointing_clock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fait le'),
        ),
        migrations.AlterField(
            model_name='pointing',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='mise a jour le'),
        ),
    ]
