# Generated by Django 4.0.3 on 2022-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0009_alter_pointing_created_alter_pointing_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='qr_code'),
        ),
    ]
