# Generated by Django 4.0.3 on 2022-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0010_alter_employee_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
