# Generated by Django 4.0.3 on 2022-06-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0012_remove_employee_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pointing',
            options={'ordering': ['-id']},
        ),
    ]
