# Generated by Django 4.0.3 on 2022-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0013_alter_employee_options_alter_pointing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
